#' Generate Icon CSS from Images
#'
#' Development helper that takes a folder of images and generates CSS file
#' with icon classes. Images are copied to output folder and CSS references them.
#' Use this to add custom language flags beyond the built-in ones.
#'
#' @param images_dir Path to folder containing source images (PNG, JPG, SVG)
#' @param output_dir Path where CSS and images will be saved (e.g., "www/custom_flags")
#' @param prefix CSS class prefix (default: "language-flag-")
#' @param css_filename Name of generated CSS file (default: "custom-languages.css")
#' @param width Icon width in pixels (default: 60)
#' @param height Icon height in pixels (default: 60)
#' @param mapping Optional named list mapping filenames to class codes
#'   (e.g., \code{list("germany.png" = "de")}). If NULL, uses filename as code.
#' @param overwrite Overwrite existing files (default: FALSE)
#'
#' @return Invisibly returns list with generated CSS path and icon names
#'
#' @examples
#' \dontrun{
#' # Add custom language flags
#' generate_icon_css(
#'   images_dir = "raw_images/flags",
#'   output_dir = "www/custom_flags",
#'   prefix = "language-flag-",
#'   mapping = list(
#'     "germany.png" = "de",
#'     "italy.png" = "it"
#'   )
#' )
#'
#' # Then in your app, include the CSS:
#' # tags$link(rel = "stylesheet", href = "custom_flags/custom-languages.css")
#' }
#'
#' @export
generate_icon_css <- function(
    images_dir,
    output_dir,
    prefix = "language-flag-",
    css_filename = "custom-languages.css",
    width = 60,
    height = 60,
    mapping = NULL,
    overwrite = FALSE
) {
  if (!dir.exists(images_dir)) {
    stop("images_dir does not exist: ", images_dir)
  }

  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    message("Created output directory: ", output_dir)
  }

  image_extensions <- c("png", "jpg", "jpeg", "svg", "gif", "webp")
  pattern <- paste0("\\.(", paste(image_extensions, collapse = "|"), ")$")
  image_files <- list.files(images_dir, pattern = pattern, ignore.case = TRUE)

  if (length(image_files) == 0) {
    stop("No image files found in: ", images_dir)
  }

  message("Found ", length(image_files), " images")

  css_lines <- c(
    "/* Generated by language.selector::generate_icon_css() */",
    paste0("/* Source: ", images_dir, " */"),
    paste0("/* Date: ", Sys.time(), " */"),
    "",
    "/* Base class - inherits from package */",
    ".language-flag {",
    "  background-size: contain;",
    "  background-position: center;",
    "  background-repeat: no-repeat;",
    "  vertical-align: middle;",
    "  display: inline-block;",
    "}",
    ""
  )

  icon_names <- c()

  for (img_file in image_files) {
    if (!is.null(mapping) && img_file %in% names(mapping)) {
      icon_name <- tolower(mapping[[img_file]])
    } else {
      icon_name <- tolower(tools::file_path_sans_ext(img_file))
    }
    icon_name <- gsub("[^a-z0-9]", "-", icon_name)
    icon_names <- c(icon_names, icon_name)

    src_path <- file.path(images_dir, img_file)
    dest_path <- file.path(output_dir, img_file)

    if (file.exists(dest_path) && !overwrite) {
      message("  Skipping (exists): ", img_file)
    } else {
      file.copy(src_path, dest_path, overwrite = overwrite)
      message("  Copied: ", img_file)
    }

    css_lines <- c(css_lines, paste0(
      ".", prefix, icon_name, " { background-image: url(\"", img_file, "\"); }"
    ))
  }

  css_path <- file.path(output_dir, css_filename)
  writeLines(css_lines, css_path)
  message("\nGenerated CSS: ", css_path)
  message("Icon classes: .", prefix, "<code>")
  message("\nUsage in Shiny app:")
  message('  tags$link(rel = "stylesheet", href = "',
          basename(output_dir), "/", css_filename, '")')

  invisible(list(
    css_path = css_path,
    icons = icon_names,
    prefix = prefix
  ))
}
